name: Deploy MERN App on EC2 (Self Hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move to project directory
        run: |
          cd ${{ github.workspace }}
          ls -la

      - name: Create environment file
        run: |
          cd ${{ github.workspace }}
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          cat .env

      - name: Stop existing containers
        run: |
          cd ${{ github.workspace }}
          docker-compose down || true

      - name: Build and start containers
        run: |
          cd ${{ github.workspace }}
          docker-compose up --build -d

