name: Build, Push & Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build backend image
        run: |
          docker build -t juhisinha/mern-backend:latest ./server

      - name: Build frontend image
        run: |
          docker build -t juhisinha/mern-frontend:latest ./client

      - name: Push backend image
        run: |
          docker push juhisinha/mern-backend:latest

      - name: Push frontend image
        run: |
          docker push juhisinha/mern-frontend:latest

      - name: Deploy containers on EC2
        run: |
          docker-compose down || true
          docker-compose pull
          docker-compose up -d

